INSERT INTO board(subject, content, writer, regdate) VALUES('안녕1', '오늘 날씨 좋네요', 'Alice', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕2', '점심 뭐 먹지?', 'Bob', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕3', '게임하고싶어요', 'Carol', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕4', '공부해야겠다', 'David', SYSDATE());
INSERT INTO board(SUBJECT, content, writer, regdate) VALUES('안녕5', '게임하고싶어요', 'Jangjinwoo', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕6', '백엔드공부하죠', 'Holymoly', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕7', '게임은 무슨게임이에요', 'ABCDE', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕8', '게임할 시간에 공부나 하세요', 'jason', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕9', '공부가 어려워요', 'Susanto', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕10', '저두요', 'Jinggg', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕11', '주말에 뭐하세요?', 'Emma', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕12', '오늘 하루 피곤해요', 'Frank', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕13', '커피 마시고싶어요', 'Grace', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕14', '운동 다녀왔어요', 'Henry', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕15', '맛있는거 먹고싶다', 'Irene', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕16', '오늘은 집에서 쉴래요', 'Jack', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕17', '코딩 재미있어요', 'Kim', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕18', '잠이 부족해요', 'Liam', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕19', '영화 보고싶어요', 'Mia', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕20', '책 읽는 중이에요', 'Noah', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕21', '게임 중단', 'Olivia', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕22', '친구랑 놀러갈래요', 'Peter', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕23', '오늘 날씨 흐려요', 'Quinn', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕24', '저녁 뭐 먹지?', 'Rachel', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕25', '강아지 산책', 'Steve', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕26', '피곤하지만 행복해요', 'Tina', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕27', '오늘도 화이팅!', 'Uma', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕28', '회의 길었어요', 'Victor', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕29', '주말 계획 세워야지', 'Wendy', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕30', '간단히 점심 먹었어요', 'Xander', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕31', '운동 중이에요', 'Yara', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕32', '책 다 읽었어요', 'Zane', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕33', '게임 레벨 올렸어요', 'Alice2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕34', '오늘도 코딩', 'Bob2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕35', '영화 재미있었어요', 'Carol2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕36', '커피 마셨네요', 'David2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕37', '잠시 쉬고 있어요', 'Emma2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕38', '점심 먹었어요', 'Frank2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕39', '날씨가 좋아요', 'Grace2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕40', '오늘 기분 좋네요', 'Henry2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕41', '게임 계속 하고싶어요', 'Irene2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕42', '친구랑 놀러갔어요', 'Jack2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕43', '오늘도 화이팅!', 'Kim2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕44', '공부 열심히 하자', 'Liam2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕45', '점심 맛있었어요', 'Mia2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕46', '영화 볼래요', 'Noah2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕47', '커피 한 잔 할래요', 'Olivia2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕48', '잠시 산책 다녀왔어요', 'Peter2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕49', '주말 잘 보내세요', 'Quinn2', SYSDATE());
INSERT INTO board(subject, content, writer, regdate) VALUES('안녕50', '오늘 하루 끝!', 'Rachel2', SYSDATE());
